import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const c=(v:unknown,m=12000)=>String(v??"").trim().slice(0,m);
const skill=(v:any)=>{const n=Number(v);return Number.isFinite(n)?Math.max(1,Math.min(20,Math.round(n))):1};
const overall=(v:any)=>{const n=Number(v);return Number.isFinite(n)?Math.max(5,Math.min(100,Math.round(n))):5};
async function y(messages:any[]){const k=c(Deno.env.get("YANDEX_GPT_API_KEY")||Deno.env.get("YANDEX_API_KEY")||""),f=c(Deno.env.get("YANDEX_FOLDER_ID")||"");if(!k||!f)throw Error("YandexGPT credentials are missing");const u=`gpt://${f}/${c(Deno.env.get("YANDEX_GPT_MODEL")||"yandexgpt/latest")}`;const r=await fetch("https://llm.api.cloud.yandex.net/foundationModels/v1/completion",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Api-Key ${k}`},body:JSON.stringify({modelUri:u,completionOptions:{stream:false,temperature:.1,maxTokens:"1800"},messages})});const t=await r.text();let d:any;try{d=JSON.parse(t)}catch{d=null}if(!r.ok)throw Error(`YandexGPT HTTP ${r.status}: ${d?.error?.message||t.slice(0,1000)}`);return {text:d?.result?.alternatives?.[0]?.message?.text||"",model:u}}
function pj(s:string){const x=s.trim().replace(/^```json\s*/i,"").replace(/^```\s*/i,"");try{return JSON.parse(x)}catch{const a=x.indexOf("{"),b=x.lastIndexOf("}");if(a>=0&&b>a)try{return JSON.parse(x.slice(a,b+1))}catch{}return null}}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({ok:false,error:"Method not allowed"},405);try{
 const auth=req.headers.get("Authorization");if(!auth)return json({ok:false,error:"Authorization required"},401);
 const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
 const db=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:{user}}=await db.auth.getUser();if(!user)return json({ok:false,error:"Unauthorized"},401);
 const body=await req.json(),sid=c(body.session_id,120);const {data:s,error}=await db.from("saletrening_sessions").select("id,employee_id,company_id,scenario_id,transcript").eq("id",sid).single();if(error||!s)return json({ok:false,error:"Session not found"},404);if(s.employee_id!==user.id)return json({ok:false,error:"Forbidden"},403);
 const tr=Array.isArray(s.transcript)?s.transcript:[];if(!tr.length)return json({ok:false,error:"Session transcript is empty"},400);
 const {data:scenario}=await db.from("saletrening_scenarios").select("title,description,objective,objections").eq("id",s.scenario_id).maybeSingle();
 const title=c(scenario?.title);const free=/свобод|free/i.test(title);
 const prompt=`Ты AI-тренер по продажам. ${free?"Это СВОБОДНАЯ тренировка: оцени разговор целиком; используй разные возражения только там, где это естественно, и не повторяй одно возражение после каждой реплики. Если менеджер хорошо выявил потребность, презентовал продукт, объяснил ценность, отработал возражения и довёл разговор до покупки, результат успешный.":"Это ОБЫЧНАЯ целевая тренировка: основной фокус — выбранный блок/возражение. Не занижай оценки за навыки, которые сценарий объективно не проверял; но для пяти навыков обязательно дай 1-20 только по наблюдаемым действиям в диалоге."}
Пять навыков и шкала 1-20: Выявление потребности, Работа с возражениями, Презентация ценности, Закрытие, Коммуникация. 1 — плохо; 13-16 — хорошо; 17-20 — отлично. Общий балл 5-100 = сумма пяти навыков. Для обычной целевой тренировки допустимо высокий общий балл только если проверяемые навыки выполнены; отсутствие проверки навыка не трактуй как провал.
success=true только если клиент явно готов купить/оформить и просит счёт/договор/реквизиты либо подтверждает заказ. Не выдумывай факты.
Верни ТОЛЬКО JSON строго такой структуры: {"overall_score":0,"discovery_score":0,"objection_score":0,"value_score":0,"closing_score":0,"communication_score":0,"success":false,"outcome":"","summary":"","strengths":[],"weaknesses":[],"recommendations":[]}
Сценарий: ${JSON.stringify({title,description:scenario?.description,objective:scenario?.objective,objections:scenario?.objections})}. Диалог: ${JSON.stringify(tr)}`;
 const r=await y([{role:"system",text:"Строгий профессиональный тренер продаж. Только валидный JSON."},{role:"user",text:prompt}]);const p=pj(r.text);if(!p)return json({ok:false,error:"Invalid YandexGPT JSON"},502);
 const skills={discovery_score:skill(p.discovery_score),objection_score:skill(p.objection_score),value_score:skill(p.value_score),closing_score:skill(p.closing_score),communication_score:skill(p.communication_score)};
 const calculated=Object.values(skills).reduce((a,b)=>a+b,0);const ev={overall_score:overall(calculated),...skills,success:Boolean(p.success),outcome:c(p.outcome,200),summary:c(p.summary,5000),strengths:Array.isArray(p.strengths)?p.strengths.map((x:any)=>c(x,800)).filter(Boolean):[],weaknesses:Array.isArray(p.weaknesses)?p.weaknesses.map((x:any)=>c(x,800)).filter(Boolean):[],recommendations:Array.isArray(p.recommendations)?p.recommendations.map((x:any)=>c(x,800)).filter(Boolean):[]};
 const admin=createClient(url,service);const now=new Date().toISOString();
 const {error:ue}=await admin.from("saletrening_sessions").update({total_score:ev.overall_score,ai_summary:ev.summary,ai_evaluation:ev,feedback:ev.summary,status:"completed",completed_at:now,updated_at:now}).eq("id",sid).eq("employee_id",user.id);if(ue)return json({ok:false,error:ue.message},500);
 const {error:se}=await admin.from("session_scores").upsert({session_id:sid,employee_id:user.id,company_id:s.company_id,overall_score:ev.overall_score,discovery_score:skills.discovery_score,objection_score:skills.objection_score,value_score:skills.value_score,closing_score:skills.closing_score,communication_score:skills.communication_score}, {onConflict:"session_id"});
 if(se)return json({ok:false,error:`Session score save failed: ${se.message}`},500);
 return json({ok:true,provider:"yandexgpt",model:r.model,evaluation:ev});
}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});